conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import home_page_view, add_post_view, post_detail_view, comment_view

app_name = 'posts'

urlpatterns = [
    path('add/post/', add_post_view, name='add'),
    path('post/<int:pk>/', post_detail_view, name='detail'),
    path('post/comment/<int:pk>/', comment_view, name='comment'),
    path('', home_page_view, name='home'),
]

users/urls.py
from django.urls import path

from users.views import register_view, login_view, logout_view, user_profile, verify_code_view, update_user_view, \
    following_view, get_user_by_username

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', user_profile, name='profile'),
    path('verify/', verify_code_view, name='verify'),
    path('update/', update_user_view, name='update'),
    path('follow/<int:pk>/w', following_view, name='follow'),
    path('username/<int:pk>/', get_user_by_username, name='username'),
]

templates/add-post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        form {
            background-color: #ffffff;
            padding: 20px;
            width: 300px;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: calc(100% - 22px);
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px 20px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
<form action="{% url 'posts:add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add photo</button>
</form>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse px-5 mb-3" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Online Gallery</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:profile' %}">Profile <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:home' %}">Global</a>
            </li>
        </ul>
        <form method="get" class="form-inline my-2 my-lg-0">
            <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" value="{{ request.GET.q }}" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if request.user.is_authenticated %}
            <button class="btn btn-outline-success my-2 my-sm-0 ml-3" type="submit">
             <a href="{% url 'users:logout' %}">
                Logout
            </a>
            </button>

            <button class="btn btn-outline-success my-2 my-sm-0 ml-3" type="submit">
             <a href="{% url 'posts:add' %}">
                Add photo
            </a>
            </button>
        {% else %}
            <button class="btn btn-outline-success my-2 my-sm-0 ml-3" type="submit">
                <a href="{% url 'users:login' %}">
                    Login
                </a>
            </button>
        {% endif %}
        <button class="btn btn-outline-success my-2 my-sm-0 ml-3" type="submit">
            <a href="{% url 'users:register' %}">
                Register
            </a>
        </button>
    </div>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<h1>Salom</h1>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

{% include 'header.html' %}

<div class="container">
    <div class="card-deck mb-3 mt-3">
        {% for post in posts %}
            <div class="card w-25">
                <a href="{% url 'posts:detail' pk=post.id %}">
                    <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
                </a>

                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <a href="{% url 'users:username' pk=post.user.id %}">
                        <p class="card-text">{{ post.user.username }}</p>
                    </a>

                    <p class="card-text"><small class="text-muted">{{ post.created_at|date }}</small></p>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example ">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="container">
        <h2>User Login</h2>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

templates/others-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f9f9f9;
      margin: 0;
      padding: 0;
    }
    .container {
      margin-top: 20px;
    }
    header {
      display: flex;
      align-items: center;
    }
    .profile-picture {
      margin-right: 20px;
    }
    .profile-info h1 {
      font-size: 24px;
      margin: 0;
    }
    .profile-info p {
      margin: 0;
    }
    .profile-stats {
      list-style: none;
      padding: 0;
      margin-top: 10px;
    }
    .profile-stats li {
      display: inline-block;
      margin-right: 10px;
      font-size: 14px;
    }
    .gallery {
      margin-top: 20px;
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 10px;
    }
    .gallery-item {
      border: 1px solid #ccc;
      border-radius: 5px;
      overflow: hidden;
    }
    .gallery-item img {
      width: 100%;
      height: auto;
      display: block;
    }
    .btn-primary {
      background-color: #007bff;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    .btn-primary:hover {
      background-color: #0056b3;
    }
    .btn-secondary {
      background-color: #6c757d;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    .btn-secondary:hover {
      background-color: #5a6268;
    }
  </style>
</head>
<body>
{% include 'header.html' %}
<div class="container">
  <header>
    <div class="profile-picture">
      <img src="{{ user.avatar.url }}" alt="Profile Picture">
    </div>
    <div class="profile-info">
      <h1>@{{ user.username }}</h1>
      <h1>{{ user.first_name }}</h1>
      <p>{{ user.bio }}</p>
      <ul class="profile-stats">
        <li><strong>{{ user.posts.count }}</strong> posts</li>
        <li><strong>100k</strong> followers</li>
        <li><strong>{{ user.whom.count }}</strong> following</li>
      </ul>
    </div>
    <div>
      <button class="btn-primary"><a href="{% url 'users:update' %}" style="color: #fff; text-decoration: none;">Update profile</a></button>
      <button class="btn-secondary"><a href="{% url 'users:follow' pk=user.id %}">Follow</a></button>
    </div>
  </header>
  <div class="gallery">
    <!-- Gallery Images -->
    {% for post in user.posts.all %}
    <div class="gallery-item">
      <img src="{{ post.image.url }}" alt="Image 1">
    </div>
    {% endfor %}
    <!-- Add more images here -->
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/post-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

{% include 'header.html' %}

<div class="container">
    <img width="600" height="300" src="{{ post.image.url }}" alt="">
<h1>{{ post.title }}</h1>
<p>{{ post.description }}</p>
    {% if request.user.is_authenticated %}
<form action="{% url 'posts:comment' pk=post.id %}?next={{ request.path }}" method="post">
{% csrf_token %}
    <textarea style="width: 600px" name="comment">

    </textarea>
    <button type="submit">Comment</button>e
</form>
    {% endif %}

<ul>
    {% for comment in comments %}
    <li>
        <h3>{{ comment.user.username }}</h3>
        <p>{{ comment.comment }}</p>
    </li>
    {% endfor %}
</ul>

</div>




<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f9f9f9;
      margin: 0;
      padding: 0;
    }
    .container {
      margin-top: 20px;
    }
    header {
      display: flex;
      align-items: center;
    }
    .profile-picture {
      margin-right: 20px;
    }
    .profile-info h1 {
      font-size: 24px;
      margin: 0;
    }
    .profile-info p {
      margin: 0;
    }
    .profile-stats {
      list-style: none;
      padding: 0;
      margin-top: 10px;
    }
    .profile-stats li {
      display: inline-block;
      margin-right: 10px;
      font-size: 14px;
    }
    .gallery {
      margin-top: 20px;
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 10px;
    }
    .gallery-item {
      border: 1px solid #ccc;
      border-radius: 5px;
      overflow: hidden;
    }
    .gallery-item img {
      width: 100%;
      height: auto;
      display: block;
    }
    .btn-primary {
      background-color: #007bff;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    .btn-primary:hover {
      background-color: #0056b3;
    }
    .btn-secondary {
      background-color: #6c757d;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    .btn-secondary:hover {
      background-color: #5a6268;
    }
  </style>
</head>
<body>
{% include 'header.html' %}
<div class="container">
  <header>
    <div class="profile-picture">
      <img src="{{ request.user.avatar.url }}" alt="Profile Picture">
    </div>
    <div class="profile-info">
      <h1>@{{ request.user.username }}</h1>
      <h1>{{ request.user.first_name }}</h1>
      <p>{{ request.user.bio }}</p>
      <ul class="profile-stats">
        <li><strong>{{ request.user.posts.count }}</strong> posts</li>
        <li><strong>100k</strong> followers</li>
        <li><strong>{{ request.user.whom.count }}</strong> following</li>
      </ul>
    </div>
    <div>
      <button class="btn-primary"><a href="{% url 'users:update' %}" style="color: #fff; text-decoration: none;">Update profile</a></button>
      <button class="btn-secondary">Follow</button>
    </div>
  </header>
  <div class="gallery">
    <!-- Gallery Images -->
    {% for post in user_posts %}
    <div class="gallery-item">
      <img src="{{ post.image.url }}" alt="Image 1">
    </div>
    {% endfor %}
    <!-- Add more images here -->
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="container">
        <h2>User Registration</h2>
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="first_name">First Name:</label>
                <input type="text" id="first_name" name="first_name" required>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" id="last_name" name="last_name" required>
            </div>
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password1" required>
            </div>
            <div class="form-group">
                <label for="confirm_password">Confirm Password:</label>
                <input type="password" id="confirm_password" name="password2" required>
            </div>
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>

templates/update-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }
        form {
            margin: 50px auto;
            width: 80%;
            max-width: 600px;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        form input[type="text"], form input[type="password"], form input[type="email"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        form input[type="file"] {
            margin-top: 10px;
        }
        form button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        form button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<form action="{% url 'users:update' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
<button type="submit"><a href="{% url 'users:profile' %}">Back</a></button>
</body>
</html>

templates/user-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <header class="container">
        <div class="profile">
            <img src="img/user.jpg" alt="we"/>
        </div>
            <div class="nick">
                <div class="box">
                    <h1>sanjarbek.ai</h1>
                <button>Update profile</button>
                <button>Show archive</button>
                </div>

              <div class="follow">
                  <p>1 posts</p>
                  <p>73 followers</p>
                  <p>134 followed</p>

              </div>
              <p>Sanjarbek</p>
              <p class="desc"> 3:145</p>
              <p>Samarqand Darvoza</p>
              <a href="https://t.me/Muhammadali_0797"><p>TG kanal</p></a>
            </div>

    </header>
    <main class="container">
        <hr>
        <section class="stories">
             <div class="story">
                 <img src="" alt="story"/>
             </div>
             <div class="story">
                <img src="" alt="story"/>
            </div>
            <div class="story">
                <img src="" alt="story"/>
            </div>
        </section>
    </main>

</body>
</html>

templates/verify-code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Sizning pochtangizga tasdiqlash kodi yuborildi.</h1>
<form action="{% url 'users:verify' %}" method="post">
    {% csrf_token %}
    <input name="code" required>Enter code</input>
    <button type="submit">Send</button>
</form>
<ul>
    {% for message in messages %}
        <li>{{ message }}</li>
    {% endfor %}
</ul>
</body>
</html>